### ISSUE TITLE
Crash typing into JEI - with Optifine

### ISSUE THREAD

**Issue by kera-wolfie** [Divine-Journey-2/main#228] opened 2021-09-04 20:57 UTC
**Modpack version:**
2.2.0

**Java version:**
1.8.0_51

**Description:**
Preface by saying I have Optifine installed.
Going to type in the jei search bar caused the game to crash. VanillaFix states it could have been /dank/null, CodeChicken Lib, JEI. Crash report showed that the game crashed due to a dank rendering on the jei screen. reloading game and trying to open any inventory caused the game to crash. Removing Optifine from the modpack allowed me to load and view my inventory again. Looking up danks in jei didn't cause a crash after removing Optifine.

**When did the crash happen?**
Going to type into JEI

**Steps to reproduce:**
Can't. I re-installed a fresh version of Optifine, and it isn't crashing this time. Looked through all pages of JEI and it was fine

**Minecraft crash report:**
https://pastebin.com/9NLUTLb9
(The page shows up blank after making it. not sure if it's just on my end.)
[crash-2021-09-04_13.02.30-client.txt](https://github.com/Divine-Journey-2/main/files/7110512/crash-2021-09-04_13.02.30-client.txt) (attaching the document in case the pastebin doesn't work.)

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
I dedicated 8 or 10 GBs and my PC has 32 GBs of RAM. (I set it to 10 GB but the loading screen shows the max as 8GB)

**Additional context:**
Removing Optifine, updating the JEI search to remove any danks, and then re-installing Optifine made everything work fine again. I prefer to use Opfine, but if a similar crash happens again, I'll just remove it.
I not using any shaders at the time of crash, but was using them just moments before, but turned them off as they were having issues.

**Comment by WaitingIdly** [comment] 2021-09-04 20:58
If you are using Curseforge:
Curseforge has a long standing bug that is not possible for you to work around. whenever you start up minecraft, it will start running Java 1.8.0_51, which is a Java version released in 2015. The most recent 1.8 Java version (at the time of writing), 1.8.301, was released on July 20th 2021.
Due to this severe difference in time and version, you will frequently run into bugs when your launcher is Curseforge that you would not otherwise. 
For bug reports, please confirm that the bug occurs when using the most up to date Java version.

**Comment by Atricos** [comment] 2021-09-04 21:01
So just trying make sure I understand.
- It's a bug you had with a (potentially older) OptiFine version,
- that you can no longer reproduce,
- that doesn't happen in the base modpack.

I don't think I can do anything about that.

**Closed by Atricos** 2021-09-04 21:01 UTC
Labels: Crash

**Comment by kera-wolfie** [comment] 2021-09-04 21:04
Yes I am using Curseforge. I was not aware it used an older version of Java.
And yes Atricos. Figured I would share just in case, though didn't expect a solution.
