### ISSUE TITLE
Dark Soularium recipe doesn't work as intended.

### ISSUE THREAD

**Issue by Dispryx** [Divine-Journey-2/main#318] opened 2021-09-18 19:06 UTC
Modpack version:
2.3.1

Description:
The recipe can be made in an alloy smelter using any number of dark steel/soularium under the required amount. 
Example : 1 dark steel, 2 soularium, 1 elevatium.

Steps to reproduce:
1. Place any number under the required amount needed to make the recipe inside the alloy smelter. ( Only works on dark steel/ soularium )

Expected behavior:
Expected the recipe to work as intended.

**Comment by WaitingIdly** [comment] 2021-09-18 19:07
Closed and marked as duplicate of https://github.com/Divine-Journey-2/main/issues/299

**Closed by WaitingIdly** 2021-09-18 19:07 UTC
Labels: Bug

**Comment by Atricos** [comment] 2021-09-18 22:00
Fixed in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), along with like 30 other Alloy Smelter recipes that could be cheesed.
