### ISSUE TITLE
Framed compacting drawers

### ISSUE THREAD

**Issue by RealLith** [Divine-Journey-2/main#594] opened 2021-12-23 22:30 UTC
**Modpack version:**
2.9.1

**Describe the request:**
Framed compacting drawers.

**Reasons why this should be added:**
Just like there are framed drawers, for items, so they would fit nicer into a base design, a framed compacting drawer would be nice for same reason - compact the items AND fit into a base design.
as of right now, there is only a compacting drawers that is ugly Gray.
There is a mod thats add ONLY this 1 items "Frames compacting drawers" that adds just that of what i described. Nothing more - nothing less. 
https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers

**Describe alternatives you've considered:**
There are no alternatives to compacting drawers nicer design. Either run auto crafts for it (more machines, for TPS eating, etc) or use ugly default compacting drawer design.

**Additional context:**
Not game changing,
only 1 extra item,
just for general base designs,
no new functions.

**Comment by WaitingIdly** [comment] 2021-12-23 22:31
Duplicate of #322

**Closed by WaitingIdly** 2021-12-23 22:31 UTC
Labels: Feature Request, Mod Request
