### ISSUE TITLE
Hello! I have just started playing and it is a great modpack, although occasionaly my inventory will begin to glitch out and the items will display in my hotbar but as soon as I try to place it, it will try to eneact with the item I had before, and then the item I tried to place originally will be back in it's spot before I moved it to my hotbar, or just straight up dissapear. Any help?

### ISSUE THREAD

**Issue by Colbman03** [Divine-Journey-2/main#606] opened 2022-01-25 00:18 UTC
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.X.X

**Description:**

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Get the item ... / Go to ... / Open the ... / Place a ... / Break a ... / ...
3. ...
4. ... doesn't craft correctly. / Can't get the ... / ... can't be completed. / ...

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. These can also be attached to the "Description" or "Step to reproduce" sections. If you have no screenshots, this part can be removed.

**Additional context:**

**Comment by King65868** [comment] 2022-01-25 01:55
You have an inventory desyc, relog and that will be fixed

**Comment by Ringedtech203** [comment] 2022-01-25 04:14
Remove/change the keybind for inventory sorting(default 'r') It may not completely get rid of the issue but I have found that most desync issues are caused by that keybind

**Closed by Ringedtech203** 2022-01-25 04:14 UTC
Labels: Bug
