### ISSUE TITLE
Cannot Chisels and Bits a Chiseled block

### ISSUE THREAD

**Issue by supernicktendo64** [Divine-Journey-2/main#344] opened 2021-09-23 04:03 UTC
Weirdly, on version 2.4.0 on a Server, you cannot Chisel a Chiseled block from Chisel and Bits.

You can turn a regular block into a chiseled block by left clicking with a chisel once, but after that you cannot modify the chiseled block. So you cannot make more than one modification.

You can add bits just fine, just not remove.

This also happens when using bits instead of the chisel to remove. Same result.

**Comment by WaitingIdly** [comment] 2021-09-23 05:07
Duplicate of #280. Please use and fill out a template when opening issues.

**Closed by WaitingIdly** 2021-09-23 05:07 UTC
Labels: Duplicate
