### ISSUE TITLE
Infinite Soul of the Dark Realm When Crafting in AE Terminal

### ISSUE THREAD

**Issue by ChaosFiller** [Divine-Journey-2/main#645] opened 2022-03-21 11:32 UTC
### Modpack version

2.13.0

### Description

When using crafting Soul of the Dark Realm using the Soul Extractor and Sacthoth's Soul Reaper Blade in the AE2 Crafting Terminal, the soul count on the blade does not decrease allowing for infinite soul extraction. Durability is properly used on the extractor however.

### Steps to reproduce

1. Kill a monster using Sacthoth's Soul Reaper Blade
2. In an AE2 Crafting Terminal, craft the Soul of the Dark Realm
3. Durability decreases on the Soul Extractor and you get an equivalent amount of Souls, but the soul count on the blade never decreases.

### Expected behavior

Soul count on the blade should decrease as it does with normal crafting.

**Comment by WaitingIdly** [comment] 2022-03-21 11:55
duplicate of #371

**Closed by WaitingIdly** 2022-03-21 11:55 UTC
Labels: Bug, Duplicate
