### ISSUE TITLE
Disable Nether cities from BetterNether due to server freezes during auto save

### ISSUE THREAD

**Issue by NLBlacky** [Divine-Journey-2/main#244] opened 2021-09-06 17:08 UTC
**Modpack version:**
2.2.0

**Describe the request:**
Disable Nether cities from BetterNether by default for server/client files. This is the option **B:CityEnabled=false** in **betternether.cfg**. BetterNether has been giving alot of server performance issues (freezes from 5 seconds up to a minute) since it is trying to write alot of data from cities to a file during every world save, even if there were no changes since last auto save. More details can be found [in this Github issue report in BetterNether Github](https://github.com/paulevsGitch/BetterNether/issues/50). [This is an example of one of my own Spark tests](https://spark.lucko.me/HAoLPhWErF) that will show that there is a very high CPU usage when the world is being saved, caused by BetterNether.

**Reasons why this should be added:**
It has taken me and many others alot of time to figure out why our servers were performing soo badly every now and then. Only after figuring out it was during the auto save and after monitoring the auto save we noticed that BetterNether was using up loads of CPU during the saving, which caused the server freezes (5 seconds and more). It would save others alot of debugging time if this config setting would be disabled by default in this modpack. I even think that singleplayer performance might be improved as I suspect they will have freezes as well, but less noticeable than servers.

**Additional context:**
I'm unsure if there is any quest progression that will require the Nether cities. If there is, I would highly suggest to adjust those quests as it is not worth the constant freezes.

**Comment by TheBuzzAldrin** [comment] 2021-09-06 17:13
I just wanted to confirm this fix from another server owner. We have a server with a regular population of 6+ players, and we were experiencing massive lag spikes repeatedly that made the server nearly unplayable.

After disabling the nether city generation and regenerating the nether from scratch, we can confirm that our repeating lag spikes have vanished and the server is back to a playable state. I would highly recommend this be made a default config change so that future people running a server will not have to experience and diagnose this issue. Thank you for your time and for bringing this issue to light, our community is extremely grateful.

**Comment by BodiwNz** [comment] 2021-09-06 17:44
Another server (LvLmeUP community) with 5-10 players , disabling nether cities instantly removed a  4 second lagspike each 40s that has been sticking with the server for a long time

**Comment by ToasterKoishi** [comment] 2021-09-07 01:02
Nether cities are not required for progression. I highly recommend disabling them, as this pattern of lag spike was also occurring in the beta test server, making it extremely hard to play at times, and likely was caused by the same issue.

**Comment by Pexon94** [comment] 2021-09-08 21:34
How do I disable the BetterNether mod? Everytime someone joins the nether, the server just dies.

**Comment by Caedis** [comment] 2021-09-08 22:40
@Pexon94 No, just disable city generation in the config file. BetterNether is still needed for quests

**Comment by Pexon94** [comment] 2021-09-08 22:54
Alright, thanks!

**Comment by Pexon94** [comment] 2021-09-09 12:05
I disabled BetterNether City generation an generated a new Nether and the server still laggs and then dies... I don´t know what to do to be honest

**Comment by Caedis** [comment] 2021-09-09 12:42
@Pexon94 Can you post your error log along with the specs of the server (including how much RAM is given to DJ2)? Also, exactly which config did you disable in the `betternether.cfg` file?

**Comment by Pexon94** [comment] 2021-09-09 12:53
[crash-2021-09-09_14.02.10-server.txt](https://github.com/Divine-Journey-2/main/files/7136598/crash-2021-09-09_14.02.10-server.txt)
The server got 16 gbs of RAM, the other specs I can´t tell..But it runs smoothly until the nether. 
I just disabled the generation for Nether Cities, thats all

**Comment by Caedis** [comment] 2021-09-09 12:56
Oh, have the server owner set max-tick-time to -1 in the server.properties file. That will fix the "crashes" (the same is taking longer than a minute which is the default watchdog limit (time which the server will restart if a tick takes longer than))

**Comment by Pexon94** [comment] 2021-09-09 13:07
The server tps still drops down to 3...

**Comment by Caedis** [comment] 2021-09-09 13:10
Don't know what else to try as my server doesn't have this issue. (docker container with a 3900X + 6-10GB allocated + ran off nvme store)

**Comment by Pexon94** [comment] 2021-09-09 13:11
Thats so weird.. I hope this get fixed in the next patch..

**Comment by NLBlacky** [comment] 2021-09-09 14:42
Please try to avoid long discussions here about server performance when the issue doesn’t seem related to this topic. Feel free to ping me (NLBlacky) in DJ2 Discord (servers channel) so we can start troubleshooting your issue.

**Comment by Atricos** [comment] 2021-09-09 17:28
Disabled Better Nether Cities in 2.3.0.

If you're still having trouble, try to change the server tick time to -1 (or alternatively just a much larger than base value) in `server.properties`, and/or give your server more RAM (if you can).

**Closed by Atricos** 2021-09-09 17:28 UTC
Labels: Feature Request
