### ISSUE TITLE
Farming Station Warning Request

### ISSUE THREAD

**Issue by YuToxic** [Divine-Journey-2/main#603] opened 2022-01-14 19:29 UTC
**Modpack version:**
2.10.0

**Describe the request:**
I would like to see a Warning on the Farming station quest as if it farms crops from crop sticks the server/world will instantly crash.

**Reasons why this should be added:**
A big heads up for players before trying to farm from crop sticks using the farming station

**Describe alternatives you've considered:**
"WARNING: Farming with the Farming Station should not be used for farming seeds that use Crop Sticks as this will crash your server/world!"

**Additional context:**
This would help other players to not crash their server and end up in a bigger problem where the server/world instantly crashes. And others would receive a heads up before getting to use the Crop Sticks.

**Comment by luciscout** [comment] 2022-01-14 20:44
Duplicate of #602

**Comment by YuToxic** [comment] 2022-02-09 20:39
@Atricos is this a possibility?

**Comment by Atricos** [comment] 2022-02-16 23:45
I tested it and yup, the Farming Station crashes the game when it's trying to harvest a Crop Sticked crop.

So I added warnings as a tooltip on the Farming Station and also in the Crop Sticks quest in 2.11.0.

**Closed by Atricos** 2022-02-16 23:45 UTC
Labels: Feature Request
