### ISSUE TITLE
Add Roots' Wildwood Planks and Log to the enabled blocks for Chisel and Bits.

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#475] opened 2021-10-16 20:44 UTC
**Modpack version:**
2.8.0

**Describe the request:**
Add Roots' Wildwood Planks and Log to the enabled blocks for Chisel and Bits.
I have already disabled the configs that checks for tool and level of the chisel and still can't chisel them

**Reasons why this should be added:**
It is a normal block that doesn't do anything special except for looking good, so there is no reason it should not be chiselable.

**Comment by WaitingIdly** [comment] 2021-10-17 02:35
Appears to be a duplicate of #280.

**Closed by WaitingIdly** 2021-10-17 02:35 UTC
Labels: Duplicate, Feature Request
