### ISSUE TITLE
Better Nether crash on server

### ISSUE THREAD

**Issue by W1nter-isHere** [Divine-Journey-2/main#238] opened 2021-09-05 14:44 UTC
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.1.1

**Java version:**
1.8.0_291 (ex. "11.0.8")

**Description:**
Server crashed when one of the players attempted to enter nether

**When did the crash happen?**
During chunk generation of the nether

**Steps to reproduce:**
1. Get into the world
2. Enter nether

**Minecraft crash report:**
https://pastebin.com/R5VYXhrP
(You can attach any number of them, but please describe when each of them occurred.)

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
Server has 8GB of ram.
**Screenshots:**

**Additional context:**
This does not happen for every player that enters the nether.

**Comment by WaitingIdly** [comment] 2021-09-05 14:46
Closed and marked as duplicate of https://github.com/Divine-Journey-2/main/issues/158, please update to 2.2.0 and see if it occurs again.

**Closed by WaitingIdly** 2021-09-05 14:46 UTC
Labels: Duplicate, Crash

**Comment by W1nter-isHere** [comment] 2021-09-05 14:55
are you sure this is a duplicate? #158 is caused by recurrent complex, this one is caused by better nether.

**Comment by Caedis** [comment] 2021-09-05 15:06
should still test with the latest version before submitting issues

**Comment by Atricos** [comment] 2021-09-05 15:17
The Better Nether generation could be pretty intense, so make sure the server CPU isn't occupied with too many other things during the initial generation.

**Comment by Atricos** [comment] 2021-09-05 15:28
Reading the crash report, it seems a Better Nether City took way longer to generate than expected. Try to set the server tick time to -1 (or alternatively just a much larger than base value) in `server.properties`.

**Comment by W1nter-isHere** [comment] 2021-09-05 16:16
Yea I tried making Mac server tick longer and that seem to do the job.
