### ISSUE TITLE
Crafted Abyssalnomicon doesn't count towards Quest "The collection's complete"

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#296] opened 2021-09-14 21:36 UTC
**Modpack version:**
2.3.1

**Description:**
Quest 25 only accepts an Abyssalnomicon that is different to a crafted one

**Steps to reproduce:**
1. Finish quest 51 "The Gatekeeper's Promise"
2. (alternative 1) Get an omothol necronomicon and fill it with some PE (any amount >0 is enough)
2. (alternative 2) Craft up an omothol necronomicon without opening it and without filling it with PE
3. Upgrade that necronomicon to abyssalnomicon
4. Quest won't complete even on Detect/Submit press

**Expected behavior:**
The quest should get completed
probably by allowing any nbt

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/57828910/133336789-02d4d683-a842-4665-9388-aa751dbd6075.png)
![grafik](https://user-images.githubusercontent.com/57828910/133336804-c6c78a5e-a978-4d66-9ce0-ca47d026267c.png)

**Comment by luciscout** [comment] 2021-09-14 22:27
Adding onto this - crafting with 0 doesn't work either.

**Comment by JohanniklasLp** [comment] 2021-09-14 22:36
![grafik](https://user-images.githubusercontent.com/57828910/133342805-26a26f06-c859-4d0f-b181-89016e2da7d2.png)
Crafting up a completely new one also doesn't work

**Comment by Atricos** [comment] 2021-09-18 12:18
Can you make steps to reproduce the second issue? "Crafting up a completely new one also doesn't work." - I couldn't reproduce this. Of course I did cheat in some of the ingredients, but even when cheating in the Dreadlands Necronomicon, then "legitimately" crafting the Omothol Necronomicon, then again "legitimately" crafting the Abyssalnomicon does work.

**Comment by JohanniklasLp** [comment] 2021-09-18 12:24
You have to start by crafting the necronomicon, and then upgrading the crafted one to abyssalnomicon

**Comment by Atricos** [comment] 2021-09-18 15:45
I crafted the original Nectronomicon, cheating in the Books and Statues, then all the items surrounding it, etc., and I *was* able to craft the Abyssalnomicon all the way from the regular Necronomicon. I tried *with* and *without* opening each book to see if that made a difference, and I could still perform each craft.

**Comment by luciscout** [comment] 2021-09-18 15:47
Are you thinking the issue is with crafting? The crafting is fine, the quest book would not accept the crafted item.

**Comment by Atricos** [comment] 2021-09-18 15:52
Oh, okay then. Fix is on the way.

**Comment by Atricos** [comment] 2021-09-18 22:13
Fixed in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), now the quest book recognizes all four books with any PE stored in them.

**Closed by Atricos** 2021-09-18 22:13 UTC
Labels: Bug, Questbook
