### ISSUE TITLE
Cannot make patterns for Fluxpacks (Hardened, Reinforced, and Resonant)

### ISSUE THREAD

**Issue by RammyT** [Divine-Journey-2/main#348] opened 2021-09-23 18:14 UTC
**Modpack version:**
2.4.0

**Description:**
When trying to make patterns for the Hardened, Reinforced and/or Resonant Fluxpack, you either do not get a result or the pattern is invalid.

**Steps to reproduce:**
Make a small ME system with a Pattern Terminal.
Try to make patterns for any of the 3 Fluxpacks stated above.

**Expected behavior:**
I would expect them to be valid patterns

**Screenshots:**
![image](https://user-images.githubusercontent.com/72321012/134561460-5c8f384a-9a82-4eb5-ba22-2f4f997e4839.png)
![image](https://user-images.githubusercontent.com/72321012/134561487-f9ff7414-251a-4cb9-81f1-e3b8875e8082.png)
![image](https://user-images.githubusercontent.com/72321012/134561523-12ddc947-cf3d-4bbb-9209-603826b5a7fa.png)
![image](https://user-images.githubusercontent.com/72321012/134561548-f0cb1321-bb0a-4fb2-867d-1e0b9ad40c9e.png)
![image](https://user-images.githubusercontent.com/72321012/134561572-75c1adee-75d1-4ff3-8a8b-25ee5d6ce8d3.png)
![image](https://user-images.githubusercontent.com/72321012/134561593-c8622f66-ea2e-4c00-b796-c8dc7a6dbe48.png)
![image](https://user-images.githubusercontent.com/72321012/134562989-bb4e7e0f-ca9a-4087-af88-bb1d8e281ac7.png)

**Comment by RammyT** [comment] 2021-09-23 18:31
Upon further crafting and making patterns, it seems that all of the jetpack patterns have an NBT issue where the recipe you shiftclick in to the pattern crafts an item with atleast 1 NBT tag but the items requiring a jetpack asks for ones with 0 NBT tags, making the craft not possible.

**Comment by FakeDomi** [comment] 2021-09-23 18:36
That's a long standing issue in AE, you need to work upwards and manually place the previous tier/whatever nbt item you are using from your item storage into the pattern. Using the plus button doesn't work.

**Comment by RammyT** [comment] 2021-09-23 18:43
Can be "fixed" by manually placing the outputted items (that have the NBT tags) in the patterns that require them.
Shift clicking the pattern in will not work this way.

You can close this issue if you feel that this is good enough.

**Comment by RammyT** [comment] 2021-09-23 18:44
> ~That's a long standing issue in AE, you need to work upwards and manually place the previous tier/whatever nbt item you are using from your item storage into the pattern. Using the plus button doesn't work.~
> Sorry, mistook that for a different issue.

I think it is exactly what you just mentioned.

**Comment by FakeDomi** [comment] 2021-09-23 18:46
> 
> 
> > ~That's a long standing issue in AE, you need to work upwards and manually place the previous tier/whatever nbt item you are using from your item storage into the pattern. Using the plus button doesn't work.~
> > Sorry, mistook that for a different issue.
> 
> I think it is exactly what you just mentioned.

It also applies here, but I was originally thinking of auto crafting being unable to find the recipe for nbt items you didn't manually drag into the pattern.

**Comment by RammyT** [comment] 2021-09-23 18:52
> > > ~That's a long standing issue in AE, you need to work upwards and manually place the previous tier/whatever nbt item you are using from your item storage into the pattern. Using the plus button doesn't work.~
> > > Sorry, mistook that for a different issue.
> > 
> > 
> > I think it is exactly what you just mentioned.
> 
> It also applies here, but I was originally thinking of auto crafting being unable to find the recipe for nbt items you didn't manually drag into the pattern.

Yup, I believe that's what the issue is here too. The text you have crossed out is what I tried and it works like that. It jsut doesn't work straight from shift clicking the recipes from JEI because JEI recipes don't have any NBT tags but the actual items you craft do.

**Comment by Atricos** [comment] 2021-09-25 21:25
I couldn't reproduce this in Singleplayer, but I did change it so the Fluxpacks always craft with the correct NBT, and implemented it in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385. Hopefully this fixes the issue, so please test it. If it does, we can close this, otherwise I'll investigate further.

**Comment by Atricos** [comment] 2021-10-02 10:43
Did the change fix the issue on Multiplayer?

**Comment by Atricos** [comment] 2021-10-03 18:18
I will close this now. If it's still an issue, please reopen it.

**Closed by Atricos** 2021-10-03 18:18 UTC
Labels: Bug
